// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacacionesBancodeAlimentos.Context;

#nullable disable

namespace VacacionesBancodeAlimentos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260205211253_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.AsuetosFechas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdFecha")
                        .HasColumnType("int")
                        .HasColumnName("fechaId");

                    b.HasKey("Id");

                    b.HasIndex("IdFecha");

                    b.ToTable("asuetosFechas", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Calculo", b =>
                {
                    b.Property<int>("Indice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("indice");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Indice"));

                    b.Property<int>("AnioMax")
                        .HasColumnType("int")
                        .HasColumnName("anioMax");

                    b.Property<int>("AnioMin")
                        .HasColumnType("int")
                        .HasColumnName("anioMin");

                    b.Property<int>("Dias")
                        .HasColumnType("int")
                        .HasColumnName("dias");

                    b.HasKey("Indice");

                    b.ToTable("calculos", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.DiccionarioAsuetos", b =>
                {
                    b.Property<int>("IdFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFecha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFecha"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("IdFecha");

                    b.ToTable("diccionarioAsuetos", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSolicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<DateOnly>("FechaPeticion")
                        .HasColumnType("date")
                        .HasColumnName("fechaPeticion");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formato");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("empleadoId");

                    b.HasKey("IdSolicitud");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.SolicitudFecha", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("solicitudId");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.HasKey("IdSolicitud");

                    b.ToTable("solicitudesFechas", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Vacaciones", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empleadoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<int>("DiasTotales")
                        .HasColumnType("int")
                        .HasColumnName("diasTotales");

                    b.HasKey("IdEmpleado");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.AsuetosFechas", b =>
                {
                    b.HasOne("VacacionesBancodeAlimentos.Model.DiccionarioAsuetos", "DiccionarioAsuetos")
                        .WithMany("AsuetosFechas")
                        .HasForeignKey("IdFecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiccionarioAsuetos");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.SolicitudFecha", b =>
                {
                    b.HasOne("VacacionesBancodeAlimentos.Model.Solicitud", "Solicitud")
                        .WithMany("SolicitudFechas")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.DiccionarioAsuetos", b =>
                {
                    b.Navigation("AsuetosFechas");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Solicitud", b =>
                {
                    b.Navigation("SolicitudFechas");
                });
#pragma warning restore 612, 618
        }
    }
}
