// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacacionesBancodeAlimentos.Context;

#nullable disable

namespace VacacionesBancodeAlimentos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121183006_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Calculo", b =>
                {
                    b.Property<int>("Indice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("indice");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Indice"));

                    b.Property<int>("AnioMax")
                        .HasColumnType("int")
                        .HasColumnName("anioMax");

                    b.Property<int>("AnioMin")
                        .HasColumnType("int")
                        .HasColumnName("anioMin");

                    b.Property<int>("Dias")
                        .HasColumnType("int")
                        .HasColumnName("dias");

                    b.HasKey("Indice");

                    b.ToTable("calculos", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.DiccionarioFechas", b =>
                {
                    b.Property<int>("IdFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFecha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFecha"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("IdFecha");

                    b.ToTable("diccionarioFechas", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEmpleado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSolicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<DateOnly>("FechaPeticion")
                        .HasColumnType("date")
                        .HasColumnName("fechaPeticion");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formato");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("empleadoId");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.SolicitudFecha", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("solicitudId");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.HasKey("IdSolicitud");

                    b.ToTable("solicitudesFechas", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Vacaciones", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("empleadoId");

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<int>("DiasTotales")
                        .HasColumnType("int")
                        .HasColumnName("diasTotales");

                    b.HasKey("IdEmpleado");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Solicitud", b =>
                {
                    b.HasOne("VacacionesBancodeAlimentos.Model.Empleado", "Empleado")
                        .WithMany("Solicitud")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.SolicitudFecha", b =>
                {
                    b.HasOne("VacacionesBancodeAlimentos.Model.Solicitud", "Solicitud")
                        .WithMany("SolicitudFechas")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Vacaciones", b =>
                {
                    b.HasOne("VacacionesBancodeAlimentos.Model.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Empleado", b =>
                {
                    b.Navigation("Solicitud");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("VacacionesBancodeAlimentos.Model.Solicitud", b =>
                {
                    b.Navigation("SolicitudFechas");
                });
#pragma warning restore 612, 618
        }
    }
}
